version: '3.3'

services:
  mysql8:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 321321
      MYSQL_DATABASE: FilmesApi
    ports:
      - "3306:3306"
    volumes:
      - Docker/MySQL/data:/var/lib/mysql
